version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/video_processing
      - CORS_ORIGINS=http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - processed_videos:/app/processed_videos

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      - MONGO_INITDB_DATABASE=video_processing

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  processed_videos:
    driver: local
